#!/usr/bin/env bash
# This script installs nginx on web-01 server.
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee usr/share/nginx/html/index.html
sudo /etc/init.d/nginx start
