#!/usr/bin/env bash
# Creates custom HTTP headers for two Nginx servers
FILE=/etc/nginx/sites-available/default
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '/listen 80 default_server;/ a \\t add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
